version: '3'
services:
  webapp:
    build: .
    ports:
      - 8090:3001
    networks:
      - edi-catalog-net
    links:
      - elasticsearch
      - redis
    depends_on:
      - elasticsearch
      - redis
    restart: always
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - edi-catalog-net
    depends_on:
      - elasticsearch
    restart: always
  elasticsearch:
    image: elasticsearch:5.6.8
    container_name: elasticsearch
    environment:
      # - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9250:9200
    networks:
      - edi-catalog-net
    restart: always
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  edi-catalog-net: